package com.mljoke.rajon.inventory

enum class Item constructor(
    val textureRegion: String, val canCraft: Boolean
) {
    ARROW_POISON("arrow_poison", true), BOW("bow", true), BOWNET("bownet", true),
    AERIE("aerie", true), AIRPOTION("airpotion", true), AIRWEED("airweed", true),
    ARBALEST("arbalest", true), ARROW("arrow", true), ARROW_FIRE("arrow_fire", true),
    ARROW_WOOD("arrow_wood", true), AXE("axe", true), BAG("bag", true),
    BALDBUSH01("baldbush01", true), BALL("ball",        true),    BAMBOO("bamboo", true),
    BAMBOOHUT01("bamboohut01", true), BAMBOOHUT02("bamboohut02", true),
    /*BAMBOOHUT03("bamboohut03"), BAMBOOITEM("bambooitem"), BAMBOOTOWER("bambootower"), BANANA("banana"), BANANAPALM("bananapalm"), BANDAGE("bandage"), BANGFUNGUS("bangfungus"),
    BARK("bark"), BARREL("barrel"), BENDABLEBRANCH("bendablebranch"), BERRIES("berries"), BERRYBUSH("berrybush"), BIGSTORAGE("bigstorage"), BIRD01("bird01"), BIRDNEST("birdnest"),
    BLOODLEAF("bloodleaf"), BLUEBLOSSOM("blueblossom"), BOARDS("boards"), BOARDWALL("boardwall"), BOARDWALLPART("boardwallpart"), BOLT("bolt"), BONE("bone"), BOTTLE("bottle"),
    BOTTLEMESSAGE("bottlemessage"), BOW("bow"), BOWNET("bownet"), BRANCH("branch"), BREAD("bread"), BROADSWORD("broadsword"), BROKEN_BOWNET("broken_bownet"), BROKEN_WELL("broken_well"),
    BUILDPLACE("buildplace"), BUILDPLACE_WATER("buildplace_water"), BULLET("bullet"), BUSH01("bush01"), BUSH02("bush02"), BUSH03("bush03"), BUSH04("bush04"), BUSH05("bush05"),
    BUSH06("bush06"), BUSH07("bush07"), BUSH08("bush08"), BUSH09("bush09"), BUSH10("bush10"), BUSH11("bush11"), BUSH12("bush12"), BUSH13("bush13"), BUSH14("bush14"),
    BUTTERFLIES("butterflies"), BUTTERFLY01("butterfly01"), BUTTERFLY02("butterfly02"), BUTTERFLYGARDEN("butterflygarden"), CACAO("cacao"), CACAOFRUIT("cacaofruit"),
    CACAOTREE("cacaotree"), CAVE("cave"), CHIEFTAIN("chieftain"), CHOCOPASTE("chocopaste"), CLAW("claw"), CLAWMONKEY("clawmonkey"), CLAWSPEAR("clawspear"), COCONUT("coconut"),
    COCONUTPALM("coconutpalm"), COFFEEFRUITS("coffeefruits"), COFFEETREE("coffeetree"), COOKIE("cookie"), CORAL01("coral01"), CORD("cord"), COTTONPLANT("cottonplant"),
    COVERING("covering"), CRAB("crab"), CRATE01("crate01"), CRYSTAL01("crystal01"), CRYSTAL02("crystal02"), CRYSTALBLADE("crystalblade"), CRYSTALROCK("crystalrock"),
    DEFENSETOWER("defensetower"), DESK("desk"), DRAGONFLY("dragonfly"), DUGOUT("dugout"), EAGLE("eagle"), EXCREMENT("excrement"), EXPLOSIVEBAIT("explosivebait"),
    EXPLOSIVEBARREL("explosivebarrel"), FEATHER("feather"), FENCE01("fence01"), FENCE02("fence02"), FENCE03("fence03"), FENCE04("fence04"), FIR01("fir01"),
    FIRE01("fire01"), FIRE02("fire02"), FIREFLY("firefly"), FIRESTONE("firestone"), FISH01("fish01"), FISH02("fish02"), FISH03("fish03"), FISHINGROD("fishingrod"),
    FISHITEM("fishitem"), FLORACARNIVORA("floracarnivora"), FLOUR("flour"), FLOWERS01("flowers01"), FLOWERS02("flowers02"), FLOWERS03("flowers03"), FLOWERS04("flowers04"),
    FLOWERS05("flowers05"), FLOWERS06("flowers06"), FLOWERS07("flowers07"), FLOWERS08("flowers08"), FLOWERS09("flowers09"), FLOWERS10("flowers10"), FLY("fly"),
    FOUNTAIN("fountain"), FRIEDFISHITEM("friedfishitem"), FRIEDMEAT("friedmeat"), FUNGUS01("fungus01"), FUNGUS02("fungus02"), FUNGUS03("fungus03"), FUNGUS04("fungus04"),
    FUNGUS05("fungus05"), GATE("gate"), GOLDBAG("goldbag"), GOLDBOW("goldbow"), GOLDNUGGET("goldnugget"), GOLDROCK("goldrock"), GRAINBUNDLE("grainbundle"),
    GRAINPILE("grainpile"), GRAPE("grape"), GRAPEVINE("grapevine"), GRAS01("gras01"), GRAS02("gras02"), GRASSHOPPER("grasshopper"), GUIDEPOST01("guidepost01"),
    GUIDEPOST02("guidepost02"), HAMMER("hammer"), HAMMOCK("hammock"), HEALTHPOTION("healthpotion"), HEMP("hemp"), HEMPLEAF("hempleaf"), HERB01("herb01"), HERB02("herb02"),
    HERB03("herb03"), HERB04("herb04"), HERBALGARDEN("herbalgarden"), HOUSE("house"), HUGEPALM01("hugepalm01"), HUT("hut"), IMMORTALPOTION("immortalpotion"), INSECTS("insects"),
    IRON("iron"), IRONBAR("ironbar"), IRONBOLT("ironbolt"), JETTY01("jetty01"), JETTY02("jetty02"), JETTY03("jetty03"), JOINT("joint"), JUICE("juice"), KEY("key"), KIWI("kiwi"),
    KIWIBREEDING("kiwibreeding"), KIWINEST("kiwinest"), LEAF("leaf"), LIANA("liana"), LIANAPALM("lianapalm"), LIANATREE("lianatree"), LION("lion"), LIONSTONE("lionstone"),
    LOCKPICK("lockpick"), LONGBOW("longbow"), MAP("map"), MARBLE01("marble01"), MARBLE02("marble02"), MARBLE04("marble04"), MATCHET("matchet"), MEADOW01("meadow01"), MEAT("meat"),
    MEDIKIT("medikit"), METALROCK("metalrock"), MONKEY("monkey"), MONKEY_CARRIER("monkey_carrier"), MONKEYSCHOOL("monkeyschool"), MOSS("moss"), NATIVE("native"), NET("net"),
    PALISADE("palisade"), PALM01("palm01"), PALM02("palm02"), PALM03("palm03"), PALM04("palm04"), PALM05("palm05"), PALM06("palm06"), PARROT("parrot"),
    PARROTNEST("parrotnest"), PASTE("paste"), PEARL("pearl"), PEBBLES("pebbles"), PICKAXE("pickaxe"), PIRANHA("piranha"), PIRATE("pirate"), PISTOL("pistol"), PLANE("plane"),
    PLUMS("plums"), POISON("poison"), POISONFLOWER("poisonflower"), PROF("prof"), RAPTOR("raptor"), RAPTORNEST("raptornest"), REED("reed"), REMOTETRIGGER("remotetrigger"),
    ROCK01("rock01"), ROCK02("rock02"), ROCK03("rock03"), ROCK04("rock04"), ROCK05("rock05"), ROCK06("rock06"), ROCKET("rocket"), ROCKETLAUNCHER("rocketlauncher"),
    ROOTS01("roots01"), ROOTS02("roots02"), RUINS01("ruins01"), RUINS02("ruins02"), RUINS03("ruins03"), RUINS04("ruins04"), RUINS05("ruins05"), RUINS06("ruins06"),
    RUINS07("ruins07"), RUINS08("ruins08"), SAILRAFT("sailraft"), SCORPION("scorpion"), SCYTHE("scythe"), SEASTAR("seastar"), SEAWEED("seaweed"), SHARK("shark"),
    SHEEP("sheep"), SHELL("shell"), SHELTER01("shelter01"), SHOTGUN("shotgun"), SIGN("sign"), SKIN("skin"), SLIME("slime"), SLINGSHOT("slingshot"), SMALLMEAT("smallmeat"),
    SMALLMEATFRIED("smallmeatfried"), SNAIL("snail"), SPADE("spade"), SPEAR("spear"), SPEEDPOTION("speedpotion"), SPIDER("spider"), STANCE("stance"), STONE01("stone01"),
    STONE02("stone02"), STONE03("stone03"), STONE04("stone04"), STONE05("stone05"), STONESTORAGE("stonestorage"), STORAGE("storage"), STRANDEDGUY("strandedguy"),
    STUMP01("stump01"), STUMP02("stump02"), STUMP03("stump03"), SWORD("sword"), TABLE("table"), TARGET("target"), TENT("tent"), TENTITEM("tentitem"), TOOTH("tooth"),
    TORCH01("torch01"), TORCH02("torch02"), TORCHITEM("torchitem"), TOXICROCKET("toxicrocket"), TRAP("trap"), TREE01("tree01"), TREE02("tree02"), TREE03("tree03"),
    TREE04("tree04"), TREE05("tree05"), TREE06("tree06"), TREE07("tree07"), TREEHOUSE("treehouse"), TRUNK("trunk"), TURTLE("turtle"), WATCH("watch"), WATER("water"),
    WATERPIPE_EMPTY("waterpipe_empty"), WATERPIPE_FULL("waterpipe_full"), WATERROCK("waterrock"), WATERROCK0("waterrock0"), WEEDGRANDPA("weedgrandpa"), WELL("well"),
    WILSON("wilson"), WINE("wine"), WOODSTORAGE("woodstorage"), WOOL("wool"), WORM("worm"), WRECK01("wreck01"), YACHT("yacht")*/

}
